console.log("hello world")
console.log("I am abdul haseeb")
console.log("45")
console.log(450)
console.log(2.45)
console.log("I am muzammil\nthis is a new line")
console.log("My name is\t \\ 'abdul haseeb'")
console.log("files added")
